/*TRANSACTION can used in InnoDB and DBD*/
SET AUTOCOMMIT=0;

START TRANSACTION;

INSERT ...;
UPDATE table2 SET summury=5 WHERE type_z=1;

COMMIT;



SET AUTOCOMMIT=0;

START TRANSACTION;

/*INSERT ...;*/
UPDATE userList SET secondName='Petrov' WHERE id=1;

COMMIT;/*ROLLBACK*/


-----------------------------
/*
READ UNCOMMITTED
READ COMMITTED
REPEATABLE READ
SERIALIZABLE

[GLOBAL | SESSION]
*/
/*PROCEDURE can utilize TRANSACTIONs*/
SET AUTOCOMMIT=0;
SET /*[GLOBAL|SESSION]*/ TRANSACTION ISOLATION LEVEL READ COMMITTED;
START TRANSACTION;
/*INSERT ...;*/
UPDATE Users SET surNameUser='Kolyan' WHERE id_user=1;
SAVEPOINT SP1;
UPDATE Users SET surNameUser='Petyha' WHERE id_user=3;
ROLLBACK TO SAVEPOINT SP1;
COMMIT;


SET AUTOCOMMIT=0;
SET GLOBAL TRANSACTION ISOLATION LEVEL READ COMMITTED;
START TRANSACTION;
/*INSERT ...;*/
UPDATE Users SET surNameUser='K' WHERE id_user=1;
SAVEPOINT SP1;
UPDATE Users SET surNameUser='Petyha' WHERE id_user=3;
ROLLBACK TO SAVEPOINT SP1;
COMMIT;


SET AUTOCOMMIT=0;
SET GLOBAL TRANSACTION ISOLATION LEVEL READ COMMITTED;
START TRANSACTION;
SAVEPOINT SP1;
UPDATE Users SET surNameUser='Kolyan' WHERE id_user=1;
SAVEPOINT SP2;
UPDATE Users SET surNameUser='Petyha' WHERE id_user=2;
ROLLBACK TO SAVEPOINT SP2;
UPDATE Users SET surNameUser='Telepuzik' WHERE id_user=3;
ROLLBACK TO SAVEPOINT SP1;
UPDATE Users SET surNameUser='Gorpina' WHERE id_user=1;

ROLLBACK;
