CREATE DATABASE IF NOT EXISTS TOYS;
	USE TOYS;


CREATE TABLE IF NOT EXISTS Users (
	id_user     INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	type_code   INT(11) DEFAULT NULL,
	name        VARCHAR(30) DEFAULT NULL,
	surName     VARCHAR(30) DEFAULT NULL,
	pass        VARCHAR(30) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS MadeGoods (
	id_made     INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	region      VARCHAR(30) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS Available (
	id_available   INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	type_available VARCHAR(30) DEFAULT NULL
);